# Generated by Django 4.0.6 on 2022-07-28 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usersapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetails',
            name='collection_end_time',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='collection_start_time',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='duty_cycle_off_interval',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='duty_cycle_on_interval',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='home_latitude',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='home_longitude',
        ),
        migrations.RemoveField(
            model_name='userdetails',
            name='num_self_report',
        ),
        migrations.AlterField(
            model_name='userdetails',
            name='study_name',
            field=models.CharField(choices=[('MHL-Demo', 'MHL-Demo')], max_length=12),
        ),
    ]
